import torch

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

BATCH_SIZE = 64
GAMMA = 0.995
LEARNING_RATE = 0.0002
MEMORY_SIZE = 100000
UPDATE_TARGET_FREQ = 500

LSTM_HIDDEN_SIZE = [256, 128, 64]
STATE_DIM = 40
ACTION_FEATURE_DIM = 256  # TRACK_POOL_SIZE と同じ（one-hotエンコーディング用）

TRACK_POOL_SIZE = 256
SESSION_LENGTH = 20

N_EPISODES = 300
EPSILON_START = 1.0
EPSILON_END = 0.1
EPSILON_DECAY = 0.998

N_TRAJECTORIES = 2000
PRETRAIN_EPOCHS = 20
PRETRAIN_BATCH_SIZE = 64

RANDOM_SEED = 42

# PPO Parameters
PPO_LR = 3e-4
PPO_GAMMA = 0.99
PPO_LAMBDA = 0.95
PPO_EPS_CLIP = 0.2
PPO_K_EPOCHS = 4
PPO_VALUE_COEF = 0.5
PPO_ENTROPY_COEF = 0.01

# Simple Graph DQN Parameters
GRAPH_FEATURE_DIM = 3  # popularity, duration, year
GRAPH_HIDDEN_DIM = 128

# Heterogeneous Graph DQN (HGT) — see models/hetero_graph_dqn.py
HETERO_HGT_HEADS = 4